#!/usr/bin/env python3

import subprocess
import numpy as np
import cv2
import os
import time

os.environ['DISPLAY'] = ':1001'

# ── BOARD SETTINGS ────────────────────────────────────────────────────────────
INNER_COLS  = 10      # inner corners horizontally
INNER_ROWS  = 7       # inner corners vertically
CHECKER_MM  = 88.65    # physical square size in mm
# ─────────────────────────────────────────────────────────────────────────────

FRAMES_NEEDED = 20
SCRIPT_DIR    = os.path.dirname(os.path.abspath(__file__))
# Path to the intrinsics file generated by your single-lens calibration script
INTRINSICS    = "/home/uav/UAV-GPS-Denied/src/uav_demo/scripts/test_only/calib_final_036/calib_intrinsics.npz"

# Termination criteria for corner refinement
CRITERIA = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# Prepare 3D object points (0,0,0), (1,0,0), (2,0,0) ... (INNER_COLS-1, INNER_ROWS-1, 0)
objp = np.zeros((INNER_ROWS * INNER_COLS, 3), np.float32)
objp[:, :2] = np.mgrid[0:INNER_COLS, 0:INNER_ROWS].T.reshape(-1, 2)
objp *= (CHECKER_MM / 1000.0) # convert to meters

print("Loading intrinsics from:", INTRINSICS)
data = np.load(INTRINSICS)
K_l  = data['K_l'];  D_l = data['D_l']
K_r  = data['K_r'];  D_r = data['D_r']

def get_next_run_dir(base):
    i = 1
    while os.path.exists(os.path.join(base, f"stereo_run_{i:03d}")):
        i += 1
    run_dir = os.path.join(base, f"stereo_run_{i:03d}")
    os.makedirs(os.path.join(run_dir, "left"),  exist_ok=True)
    os.makedirs(os.path.join(run_dir, "right"), exist_ok=True)
    return run_dir

RUN_DIR = get_next_run_dir(SCRIPT_DIR)
print(f"Saving images to: {RUN_DIR}\n")

def get_cam_proc(camera_index):
    cmd = [
        "rpicam-vid",
        "--camera", str(camera_index),
        "--codec", "mjpeg",
        "-t", "0",
        "--width", "1280",          # 720p width
        "--height", "720",          # 720p height
        "--nopreview",
        "--framerate", "60",       # Target 60fps
        "--shutter", "10000",       # Shutter speed in microseconds (1/100s = 10,000us)
        "--gain", "5.0",
        "--awb", "indoor",
        "--denoise", "cdn_off",     # Recommended for high FPS to save CPU
        "--inline",
        "-o", "-"
    ]
    return subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)

def get_frame(proc, buffer):
    while True:
        buffer += proc.stdout.read(4096)
        a = buffer.find(b'\xff\xd8')
        b = buffer.find(b'\xff\xd9')
        if a != -1 and b != -1:
            jpg    = buffer[a:b+2]
            buffer = buffer[b+2:]
            frame  = cv2.imdecode(np.frombuffer(jpg, dtype=np.uint8), cv2.IMREAD_COLOR)
            return frame, buffer

def detect_checkerboard(frame):
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, (INNER_COLS, INNER_ROWS), None)
    if ret:
        corners = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), CRITERIA)
    return ret, corners, gray

# ── Main capture loop ─────────────────────────────────────────────────────────
print("="*50)
print("  Stereo Checkerboard Calibration")
print("  Both cameras MUST see the full board simultaneously.")
print("="*50 + "\n")

proc_l = get_cam_proc(0); buf_l = b""
proc_r = get_cam_proc(1); buf_r = b""

obj_points  = [] # 3D points in real world space
img_l_points = [] # 2D points in left image plane
img_r_points = [] # 2D points in right image plane
image_size  = None
captured    = 0
last_capture_time = 0

# Set up resizable window for the "zoomed" display issue
cv2.namedWindow("Stereo Calibration", cv2.WINDOW_NORMAL)
# Optional: Set a default starting size so it's not a tiny square
cv2.resizeWindow("Stereo Calibration", 1280, 480)
try:
    while captured < FRAMES_NEEDED:
        frame_l, buf_l = get_frame(proc_l, buf_l)
        frame_r, buf_r = get_frame(proc_r, buf_r)

        frame_l = cv2.rotate(frame_l, cv2.ROTATE_180)
        frame_r = cv2.rotate(frame_r, cv2.ROTATE_180)

        found_l, corners_l, gray_l = detect_checkerboard(frame_l)
        found_r, corners_r, gray_r = detect_checkerboard(frame_r)

        if image_size is None:
            image_size = gray_l.shape[::-1]

        vis_l = frame_l.copy()
        vis_r = frame_r.copy()

        if found_l: cv2.drawChessboardCorners(vis_l, (INNER_COLS, INNER_ROWS), corners_l, found_l)
        if found_r: cv2.drawChessboardCorners(vis_r, (INNER_COLS, INNER_ROWS), corners_r, found_r)

        now = time.time()
        time_since = now - last_capture_time
        both_good = found_l and found_r

        # Display Logic
        status_color = (0, 255, 0) if both_good else (0, 0, 255)
        cv2.putText(vis_l, f"Captured: {captured}/{FRAMES_NEEDED}", (10, 30), 1, 2, (255, 255, 255), 2)
        if both_good:
            cv2.putText(vis_l, f"READY: {max(0.0, 1.0-time_since):.1f}s", (10, 70), 1, 2, (0, 255, 0), 2)

        stereo_view = np.hstack((vis_l, vis_r))
        cv2.imshow("Stereo Calibration", stereo_view)

        if cv2.waitKey(1) & 0xFF == ord('q'): break

        if both_good and time_since >= 1.0:
            obj_points.append(objp)
            img_l_points.append(corners_l)
            img_r_points.append(corners_r)

            captured += 1
            last_capture_time = now
            cv2.imwrite(os.path.join(RUN_DIR, "left", f"img_{captured:02d}.jpg"), frame_l)
            cv2.imwrite(os.path.join(RUN_DIR, "right", f"img_{captured:02d}.jpg"), frame_r)
            print(f"Captured pair {captured}!")

finally:
    proc_l.terminate(); proc_r.terminate()
    cv2.destroyAllWindows()

if captured < 10:
    print("Not enough samples. Need at least 10.")
    exit()

# ── Stereo Calibration ────────────────────────────────────────────────────────
print("\nCalculating Extrinsics (R, T)...")
# We fix intrinsics because you already calibrated them individually
flags = cv2.CALIB_FIX_INTRINSIC

ret, K_l, D_l, K_r, D_r, R, T, E, F = cv2.stereoCalibrate(
    obj_points, img_l_points, img_r_points,
    K_l, D_l, K_r, D_r,
    image_size, criteria=CRITERIA, flags=flags
)

print(f"Stereo RMS Error: {ret:.4f}")

# Rectification
R_l, R_r, P_l, P_r, Q, roi_l, roi_r = cv2.stereoRectify(
    K_l, D_l, K_r, D_r, image_size, R, T, alpha=0
)

# Generate Maps
map_lx, map_ly = cv2.initUndistortRectifyMap(K_l, D_l, R_l, P_l, image_size, cv2.CV_32FC1)
map_rx, map_ry = cv2.initUndistortRectifyMap(K_r, D_r, R_r, P_r, image_size, cv2.CV_32FC1)

# Save results
out_path = os.path.join(RUN_DIR, "calib_stereo.npz")
np.savez(out_path,
         K_l=K_l, D_l=D_l, K_r=K_r, D_r=D_r,
         R=R, T=T, E=E, F=F,
         R_l=R_l, R_r=R_r, P_l=P_l, P_r=P_r, Q=Q,
         map_lx=map_lx, map_ly=map_ly,
         map_rx=map_rx, map_ry=map_ry,
         focal_px=P_l[0,0], baseline_m=abs(T[0][0]),
         image_size=image_size)

print(f"Stereo calibration saved to: {out_path}")